# Generated by Django 6.0.3 on 2026-04-01 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='financialrecord',
            index=models.Index(fields=['record_type'], name='records_fin_record__46dc6f_idx'),
        ),
        migrations.AddIndex(
            model_name='financialrecord',
            index=models.Index(fields=['category'], name='records_fin_categor_fc12e1_idx'),
        ),
        migrations.AddIndex(
            model_name='financialrecord',
            index=models.Index(fields=['date'], name='records_fin_date_ee8369_idx'),
        ),
        migrations.AddIndex(
            model_name='financialrecord',
            index=models.Index(fields=['is_deleted'], name='records_fin_is_dele_615775_idx'),
        ),
    ]
